# Generated by Django 3.0.5 on 2020-05-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('pos_lng', models.FloatField()),
                ('pos_lat', models.FloatField()),
                ('time', models.FloatField()),
            ],
        ),
    ]
